public class Address {
    public void  homeAddress() {
        string yourName = 'Ahmet';
        system.debug('yourName:' + yourName);
        integer memberInFamily = 5;
        system.debug('memberInFamily:' + memberInFamily);
        string houseName = 'A';
        system.debug('houseName:' + houseName);
        integer houseNumber = 10;
        system.debug('houseNumber:' + houseNumber);
        string streetName = 'ABC';
        system.debug('streetName:' + streetName);
        string cityName = 'Ankara';
        system.debug('cityName:' + cityName);
        string stateName = 'ABC';
        integer stateISOCode = 06;
        string countryName = 'Turkey';
        integer countryISOCode = +90 ;
        integer zipCode = 06100;
        boolean isYoursHouse = false;
        system.debug('stateName: ' + stateName);
        system.debug('stateISOCode: ' + stateISOCode);
        system.debug('countryName: ' + countryName);
        system.debug('countryISOCode: ' + countryISOCode);
        system.debug('zipCode: ' + zipCode);
        system.debug('isYoursHouse: ' + isYoursHouse);
    }
}