public class Player {
    public void playing() {
        string player1= 'Mehmet';
        string player2= 'Ahmet';
        string player3= 'Selim';
        string player4= 'Kerim';
        string player5= 'Can';
        integer player12= 2;
        

        System.debug('Player1 Name is: ' + player1);
        System.debug('Player2 Name is: ' + player2);
        System.debug('Player3 Name is: ' + player3);
        System.debug('Player4 Name is: ' + player4);
        System.debug('Player5 Name is: ' + player5);
    }
}
