public class salesforceTRodev {
    public void odevMethod() {
        String myName = 'Samet POLAT' ;
        String satir = '.....';
        system.debug(myName);
        system.debug(satir);

        String car= 'Renault';
        String model='Megane';
        String color= 'White';
        String myCar= ' My car is '+car + ' ' + model + ' ' + color + '.' ;
        system.debug(car);
        system.debug(model);
        system.debug(color);
        system.debug(myCar);

    }
}
